- name: Install apache2 and php packages for Debian and Ubuntu
  tags: apache,apache2,debian,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: install apache and php packages for Arch Linux
  tags: apache,archlinux
  pacman:
    name:
      - apache
      - php
      - php-apache
    state: latest
  when: ansible_distribution == "Archlinux"

- name: start and enable apache (Arch Linux)
  tags: apache,archlinux,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Archlinux"

- name: change e-mail address for admin
  tags: apache,archlinux,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Archlinux"
  register: httpd

- name: restart httpd (Arch Linux)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site (Debian and Ubuntu)
  tags: apache,html
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: copy default html file for site (Arch Linux)
  tags: apache,html
  copy:
    src: default_site.html
    dest: /srv/http/index.html
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Archlinux"
